name = "site-web-aquapure-analytics"
compatibility_date = "2026-06-09"
compatibility_flags = ["nodejs_compat"]
main = ".output/server/index.mjs"

[build]
command = "npm run build"

[assets]
directory = ".output/public"
binding = "ASSETS"
