/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JumeauNumeriqueRouteImport } from './routes/jumeau-numerique'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AdminblogRouteImport } from './routes/adminblog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogueIndexRouteImport } from './routes/blogue/index'
import { Route as BlogueSlugRouteImport } from './routes/blogue/$slug'

const JumeauNumeriqueRoute = JumeauNumeriqueRouteImport.update({
  id: '/jumeau-numerique',
  path: '/jumeau-numerique',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminblogRoute = AdminblogRouteImport.update({
  id: '/adminblog',
  path: '/adminblog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogueIndexRoute = BlogueIndexRouteImport.update({
  id: '/blogue/',
  path: '/blogue/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogueSlugRoute = BlogueSlugRouteImport.update({
  id: '/blogue/$slug',
  path: '/blogue/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminblog': typeof AdminblogRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/jumeau-numerique': typeof JumeauNumeriqueRoute
  '/blogue/$slug': typeof BlogueSlugRoute
  '/blogue/': typeof BlogueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminblog': typeof AdminblogRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/jumeau-numerique': typeof JumeauNumeriqueRoute
  '/blogue/$slug': typeof BlogueSlugRoute
  '/blogue': typeof BlogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adminblog': typeof AdminblogRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/jumeau-numerique': typeof JumeauNumeriqueRoute
  '/blogue/$slug': typeof BlogueSlugRoute
  '/blogue/': typeof BlogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminblog'
    | '/confidentialite'
    | '/jumeau-numerique'
    | '/blogue/$slug'
    | '/blogue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminblog'
    | '/confidentialite'
    | '/jumeau-numerique'
    | '/blogue/$slug'
    | '/blogue'
  id:
    | '__root__'
    | '/'
    | '/adminblog'
    | '/confidentialite'
    | '/jumeau-numerique'
    | '/blogue/$slug'
    | '/blogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminblogRoute: typeof AdminblogRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  JumeauNumeriqueRoute: typeof JumeauNumeriqueRoute
  BlogueSlugRoute: typeof BlogueSlugRoute
  BlogueIndexRoute: typeof BlogueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jumeau-numerique': {
      id: '/jumeau-numerique'
      path: '/jumeau-numerique'
      fullPath: '/jumeau-numerique'
      preLoaderRoute: typeof JumeauNumeriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminblog': {
      id: '/adminblog'
      path: '/adminblog'
      fullPath: '/adminblog'
      preLoaderRoute: typeof AdminblogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogue/': {
      id: '/blogue/'
      path: '/blogue'
      fullPath: '/blogue/'
      preLoaderRoute: typeof BlogueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogue/$slug': {
      id: '/blogue/$slug'
      path: '/blogue/$slug'
      fullPath: '/blogue/$slug'
      preLoaderRoute: typeof BlogueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminblogRoute: AdminblogRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  JumeauNumeriqueRoute: JumeauNumeriqueRoute,
  BlogueSlugRoute: BlogueSlugRoute,
  BlogueIndexRoute: BlogueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
